// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: api/proto/payment/v1/payment.proto

package paymentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessTransferRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey  string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	SourceAccountId string                 `protobuf:"bytes,2,opt,name=source_account_id,json=sourceAccountId,proto3" json:"source_account_id,omitempty"`
	TargetAccountId string                 `protobuf:"bytes,3,opt,name=target_account_id,json=targetAccountId,proto3" json:"target_account_id,omitempty"`
	Amount          string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"` // Передаем как строку для сохранения точности decimal
	Currency        string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessTransferRequest) Reset() {
	*x = ProcessTransferRequest{}
	mi := &file_api_proto_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTransferRequest) ProtoMessage() {}

func (x *ProcessTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTransferRequest.ProtoReflect.Descriptor instead.
func (*ProcessTransferRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessTransferRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ProcessTransferRequest) GetSourceAccountId() string {
	if x != nil {
		return x.SourceAccountId
	}
	return ""
}

func (x *ProcessTransferRequest) GetTargetAccountId() string {
	if x != nil {
		return x.TargetAccountId
	}
	return ""
}

func (x *ProcessTransferRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *ProcessTransferRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type ProcessTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessTransferResponse) Reset() {
	*x = ProcessTransferResponse{}
	mi := &file_api_proto_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTransferResponse) ProtoMessage() {}

func (x *ProcessTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTransferResponse.ProtoReflect.Descriptor instead.
func (*ProcessTransferResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessTransferResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ProcessTransferResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessTransferResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetAccountBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountBalanceRequest) Reset() {
	*x = GetAccountBalanceRequest{}
	mi := &file_api_proto_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountBalanceRequest) ProtoMessage() {}

func (x *GetAccountBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetAccountBalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccountBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAccountBalanceResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Currency         string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	AvailableBalance string                 `protobuf:"bytes,3,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	FrozenBalance    string                 `protobuf:"bytes,4,opt,name=frozen_balance,json=frozenBalance,proto3" json:"frozen_balance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAccountBalanceResponse) Reset() {
	*x = GetAccountBalanceResponse{}
	mi := &file_api_proto_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountBalanceResponse) ProtoMessage() {}

func (x *GetAccountBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetAccountBalanceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountBalanceResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetAccountBalanceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetAccountBalanceResponse) GetAvailableBalance() string {
	if x != nil {
		return x.AvailableBalance
	}
	return ""
}

func (x *GetAccountBalanceResponse) GetFrozenBalance() string {
	if x != nil {
		return x.FrozenBalance
	}
	return ""
}

type GetTransactionStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTransactionStatusRequest) Reset() {
	*x = GetTransactionStatusRequest{}
	mi := &file_api_proto_payment_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionStatusRequest) ProtoMessage() {}

func (x *GetTransactionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransactionStatusRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type GetTransactionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorReason   string                 `protobuf:"bytes,3,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionStatusResponse) Reset() {
	*x = GetTransactionStatusResponse{}
	mi := &file_api_proto_payment_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionStatusResponse) ProtoMessage() {}

func (x *GetTransactionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *GetTransactionStatusResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *GetTransactionStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTransactionStatusResponse) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

var File_api_proto_payment_v1_payment_proto protoreflect.FileDescriptor

const file_api_proto_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/payment/v1/payment.proto\x12\n" +
	"payment.v1\"\xcd\x01\n" +
	"\x16ProcessTransferRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12*\n" +
	"\x11source_account_id\x18\x02 \x01(\tR\x0fsourceAccountId\x12*\n" +
	"\x11target_account_id\x18\x03 \x01(\tR\x0ftargetAccountId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\"w\n" +
	"\x17ProcessTransferResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"9\n" +
	"\x18GetAccountBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\xaa\x01\n" +
	"\x19GetAccountBalanceResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12+\n" +
	"\x11available_balance\x18\x03 \x01(\tR\x10availableBalance\x12%\n" +
	"\x0efrozen_balance\x18\x04 \x01(\tR\rfrozenBalance\"F\n" +
	"\x1bGetTransactionStatusRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\"\x80\x01\n" +
	"\x1cGetTransactionStatusResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\ferror_reason\x18\x03 \x01(\tR\verrorReason2\xb9\x02\n" +
	"\x0ePaymentService\x12Z\n" +
	"\x0fProcessTransfer\x12\".payment.v1.ProcessTransferRequest\x1a#.payment.v1.ProcessTransferResponse\x12`\n" +
	"\x11GetAccountBalance\x12$.payment.v1.GetAccountBalanceRequest\x1a%.payment.v1.GetAccountBalanceResponse\x12i\n" +
	"\x14GetTransactionStatus\x12'.payment.v1.GetTransactionStatusRequest\x1a(.payment.v1.GetTransactionStatusResponseBOZMgithub.com/JumpCodeFrog/fintech-payment-engine/api/proto/payment/v1;paymentv1b\x06proto3"

var (
	file_api_proto_payment_v1_payment_proto_rawDescOnce sync.Once
	file_api_proto_payment_v1_payment_proto_rawDescData []byte
)

func file_api_proto_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_api_proto_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_api_proto_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_payment_v1_payment_proto_rawDesc), len(file_api_proto_payment_v1_payment_proto_rawDesc)))
	})
	return file_api_proto_payment_v1_payment_proto_rawDescData
}

var file_api_proto_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_payment_v1_payment_proto_goTypes = []any{
	(*ProcessTransferRequest)(nil),       // 0: payment.v1.ProcessTransferRequest
	(*ProcessTransferResponse)(nil),      // 1: payment.v1.ProcessTransferResponse
	(*GetAccountBalanceRequest)(nil),     // 2: payment.v1.GetAccountBalanceRequest
	(*GetAccountBalanceResponse)(nil),    // 3: payment.v1.GetAccountBalanceResponse
	(*GetTransactionStatusRequest)(nil),  // 4: payment.v1.GetTransactionStatusRequest
	(*GetTransactionStatusResponse)(nil), // 5: payment.v1.GetTransactionStatusResponse
}
var file_api_proto_payment_v1_payment_proto_depIdxs = []int32{
	0, // 0: payment.v1.PaymentService.ProcessTransfer:input_type -> payment.v1.ProcessTransferRequest
	2, // 1: payment.v1.PaymentService.GetAccountBalance:input_type -> payment.v1.GetAccountBalanceRequest
	4, // 2: payment.v1.PaymentService.GetTransactionStatus:input_type -> payment.v1.GetTransactionStatusRequest
	1, // 3: payment.v1.PaymentService.ProcessTransfer:output_type -> payment.v1.ProcessTransferResponse
	3, // 4: payment.v1.PaymentService.GetAccountBalance:output_type -> payment.v1.GetAccountBalanceResponse
	5, // 5: payment.v1.PaymentService.GetTransactionStatus:output_type -> payment.v1.GetTransactionStatusResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_payment_v1_payment_proto_init() }
func file_api_proto_payment_v1_payment_proto_init() {
	if File_api_proto_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_payment_v1_payment_proto_rawDesc), len(file_api_proto_payment_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_api_proto_payment_v1_payment_proto_depIdxs,
		MessageInfos:      file_api_proto_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_api_proto_payment_v1_payment_proto = out.File
	file_api_proto_payment_v1_payment_proto_goTypes = nil
	file_api_proto_payment_v1_payment_proto_depIdxs = nil
}
